### PR TITLE
Merge 2.4.0 into 3.0.x

### PR DESCRIPTION
**Pull request by gsteel**
Closes #15

Resets composer.* to 2.4.x.
Resolves conflicts in test case.

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
Oh, fun:

```
Error: Argument 1 of Laminas\View\HelperPluginManager::__construct expects Interop\Container\ContainerInterface|Laminas\View\ConfigInterface|null, parent type Psr\Container\ContainerInterface provided (see https://psalm.dev/193)
```

:thinking:

**Comment by gsteel** [comment]
> Oh, fun:
> 
> ```
> Error: Argument 1 of Laminas\View\HelperPluginManager::__construct expects Interop\Container\ContainerInterface|Laminas\View\ConfigInterface|null, parent type Psr\Container\ContainerInterface provided (see https://psalm.dev/193)
> ```
> 
> 🤔

Yeah… This needs suppressing I think because it simply isn't an Interop instance, but, the helper manager won't complain - Laminas View needs updating I guess??

**Comment by boesing** [comment]
> Yeah… This needs suppressing I think because it simply isn't an Interop instance, but, the helper manager won't complain - Laminas View needs updating I guess??

It actually won't. but imho worth changing the docblock in laminas-view while conflicting with `container-interop` <1.2 (which introduced the PSR interface)

**Review by Ocramius — APPROVED** [review]
Thanks @gsteel!

**Pull request merged**
