### PR TITLE
Prepare for Renovate with reusable workflows

### PR DESCRIPTION
**Pull request by ghostwriter**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Adding Renovate to Laminas, Mezzio repositories. https://gist.github.com/weierophinney/49ca8ae2b916d898dd3d4162b26ff41b

- Configure minimum supported PHP version
- Update composer dependencies
- Update to reusable `Continuous Integration` workflow
- Update to reusable `Automatic Releases` workflow

### CODE REVIEW

**Review by Ocramius — CHANGES_REQUESTED** [review]
We should probably try fixing `psalm.xml` here (small change).

Unsure about target branch though: this could live in a minor release?

**Comment by Ocramius** [comment]
Requested @weierophinney's opinion about target branch.

**Review by Ocramius — APPROVED** [review]

**Comment by weierophinney** [comment]
Let's do this for either a 2.4.1 or 2.5.0 release, please. From what I can tell, 3.0.x doesn't contain anything over the 2.4.x branch currently, and I'm not quite sure why it was created.

**Comment by ghostwriter** [comment]
you may have to manually accept the DCO, if I were to run`$ git rebase HEAD~26 --signoff` as [instructed](https://github.com/mezzio/mezzio-laminasviewrenderer/pull/17/checks?check_run_id=5957526014), it will unnecessarily rewrite too much history.

**Comment by Ocramius** [comment]
I'll throw in a rebase tomorrow, hopefully.

The comment by @weierophinney is really old, and we had a couple releases meanwhile :D

**Review by Ocramius — APPROVED** [review]
Updating dependencies led to some simplification in code branches, and removal of an exception that is now unused :muscle: 

Thanks @ghostwriter!

**Pull request merged**
